version: 2
jobs:
  build:
      working_directory: ~/ngx-facebook/
      docker:
        - image: node:7
      steps:
        - checkout
        - restore_cache:
           key: node_modules_{{ .Branch }}_{{ checksum "package.json" }}
        - run:
           name: Install node modules
           command: npm i
        - save_cache:
           key: node_modules_{{ .Branch }}_{{ checksum "package.json" }}
           paths:
             - ~/ngx-facebook/node_modules/
        - run:
           name: Lint
           command: npm run lint
        - run:
           name: Build module
           command: npm run build:lib
        - run:
           name: Test
           command: npm test:ci
        - add_ssh_keys
        - deploy:
           name: Update docs
           command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash ./scripts/docs/update_docs.sh
            fi
